use crate::extractor::ExtractedSpec;

pub fn render_spec(spec: &ExtractedSpec) -> String {
    let mut out = String::new();

    out.push_str(&format!("# {}.proof\n", spec.product_name));
    out.push_str(
        "# Generated by PROOF bootstrap. Review all # INFERRED and # TODO: verify markers.\n\n",
    );

    out.push_str(&format!("product {} {{\n", spec.product_name));
    out.push_str("  jurisdiction: UK                # INFERRED\n");
    out.push_str("  regulator:    FCA               # INFERRED\n");
    out.push_str("  category:     deposit           # TODO: verify\n\n");

    // Interest block
    out.push_str("  interest {\n");

    if let Some(rate) = spec.base_rate {
        out.push_str(&format!("    base_rate: {:.2}%\n", rate));
    } else {
        out.push_str("    base_rate: 0.00%             # TODO: verify — could not detect rate\n");
    }

    if !spec.tiers.is_empty() {
        out.push_str("\n    tiers {\n");
        for tier in &spec.tiers {
            let threshold = format_threshold(tier.threshold);
            if tier.rate_modifier != 0.0 {
                out.push_str(&format!(
                    "      when balance >= {:<8}  rate: base_rate + {:.2}%{}\n",
                    threshold,
                    tier.rate_modifier,
                    if tier.inferred { "  # INFERRED" } else { "" }
                ));
            } else {
                out.push_str(&format!(
                    "      when balance >= {:<8}  rate: base_rate  # TODO: verify rate\n",
                    threshold
                ));
            }
        }
        out.push_str("      otherwise               rate: base_rate\n");
        out.push_str("    }\n");
    }

    if let Some(promo) = &spec.promotional {
        out.push('\n');
        out.push_str("    promotional {\n");
        out.push_str(&format!(
            "      condition:      days_since_joined <= {}\n",
            promo.days
        ));
        if promo.rate_modifier != 0.0 {
            out.push_str(&format!(
                "      rate:           base_rate + {:.2}%\n",
                promo.rate_modifier
            ));
        } else {
            out.push_str("      rate:           base_rate + 0.00%  # TODO: verify promo rate\n");
        }
        out.push_str(&format!("      expires_after:  {} days\n", promo.days));
        out.push_str("      non_renewable:  true              # INFERRED\n");
        out.push_str("    }\n");
    }

    out.push('\n');
    out.push_str("    accrual {\n");
    out.push_str("      frequency:        daily\n");
    out.push_str(&format!(
        "      basis:            ACT/{}\n",
        spec.accrual_basis
    ));
    out.push_str("      compound:         annually          # INFERRED\n");

    if let Some(min) = spec.min_payable {
        out.push_str(&format!("      minimum_payable:  GBP {:.2}\n", min));
    }

    out.push_str("    }\n");
    out.push_str("  }\n");

    // Fees block
    if !spec.fees.is_empty() {
        out.push('\n');
        out.push_str("  fees {\n");
        for fee in &spec.fees {
            out.push_str(&format!("    fee \"{}\" {{\n", fee.name));
            if fee.is_percentage {
                out.push_str(&format!("      amount:   {:.2}%\n", fee.amount));
            } else {
                out.push_str(&format!("      amount:   GBP {:.2}\n", fee.amount));
            }
            out.push_str(&format!("      waivable: {}\n", fee.waivable));
            out.push_str("    }\n");
        }
        out.push_str("  }\n");
    }

    // Protection block
    if let Some(limit) = spec.fscs_limit {
        out.push('\n');
        out.push_str("  protection {\n");
        out.push_str("    scheme: FSCS\n");
        out.push_str(&format!("    limit:  GBP {}\n", format_threshold(limit)));
        out.push_str("  }\n");
    }

    // Obligations block
    let has_obligations = spec.cooling_off.is_some() || spec.notice_days.is_some();
    if has_obligations {
        out.push('\n');
        out.push_str("  obligations {\n");
        if let Some(days) = spec.cooling_off {
            out.push_str(&format!("    cooling_off:          {} days\n", days));
        }
        if let Some(days) = spec.notice_days {
            out.push_str(&format!("    rate_change_notice:   {} days\n", days));
        }
        out.push_str("    annual_summary:       required    # INFERRED\n");
        out.push_str("  }\n");
    }

    out.push_str("}\n");
    out
}

fn format_threshold(v: f64) -> String {
    let n = v as u64;
    if n >= 1_000 {
        // Format with underscore separator
        let s = n.to_string();
        let mut result = String::new();
        for (i, ch) in s.chars().rev().enumerate() {
            if i > 0 && i % 3 == 0 {
                result.push('_');
            }
            result.push(ch);
        }
        result.chars().rev().collect()
    } else {
        format!("{}", n)
    }
}
