[package]
name    = "proof-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "proof"
path = "src/main.rs"

[dependencies]
proof-dsl        = { path = "../proof-dsl" }
proof-eval       = { path = "../proof-eval" }
proof-ingest     = { path = "../proof-ingest" }
proof-verify     = { path = "../proof-verify" }
proof-sim        = { path = "../proof-sim" }
proof-regulatory = { path = "../proof-regulatory" }
proof-bootstrap  = { path = "../proof-bootstrap" }
serde            = { workspace = true }
serde_json       = { workspace = true }
anyhow           = { workspace = true }
rust_decimal     = { workspace = true }